### ISSUE TITLE
Encrypted SNI

### ISSUE THREAD

**Issue by mrbluecoat** [luigi1809/webfilter-ng#4]
Any options for dealing with encrypted SNI?  https://blog.cloudflare.com/encrypted-sni/

**Comment by luigi1809** [comment]
@mrbluecoat thanks for your report
Encrypted SNI can not be decrypted by Man-in-the-middle.
I changed the code to drop the connection when encrypted SNI is detected (TLS extension 65486). Things gonna change as Encrypted SNI standard is a draft.

Tested with firefox 70. Cloudfare DoH + ESNI via about:config : 
* network.security.esni.enabled true
* network.trr.mode 3
* network.trr.custom_uri https://1.1.1.1/dns-query
* network.trr.uri https://1.1.1.1/dns-query

Test page : https://cloudflare.com/cdn-cgi/trace 

Unfortunately, firefox does not fallback to unencrypted SNI and the connection is dropped.

**Comment by luigi1809** [comment]
https://github.com/luigi1809/webfilter-ng/commit/d7d5fcfdbd7f05ebd945ea76e93759fb3067fe9c

**Comment by luigi1809** [comment]
I wait for encrypted SNI to be a standard to support encrypted SNI in a better way

**Comment by mrbluecoat** [comment]
Thanks for the update.  Dropping Cloudflare traffic for hosts using ESNI is a tolerable stopgap but is there any long-term solution for monitoring home/work traffic with ESNI?  Perhaps client cert approach like mitmproxy?

**Comment by luigi1809** [comment]
key to encrypt SNI is provided by DNS.

In Cloudflare current implementation of the draft RFC, the key is obtained by requesting a DNS TXT entry of the root domain name prefixed by _esni.

```
dig _esni.cloudflare.com TXT

; <<>> DiG 9.10.3-P4-Debian <<>> _esni.cloudflare.com TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42475
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_esni.cloudflare.com.		IN	TXT

;; ANSWER SECTION:
_esni.cloudflare.com.	3600	IN	TXT	"/wFF7do4ACQAHQAgWcWTew6M6glGwqxZ2wjf7xpok65Xu9FkJsrrHCJ+G1MAAhMBAQQAAAAAXc5pEAAAAABd1lIQAAA="
```
Current draft says that a ESNI DNS type is used instead of TXT.

Since ESNI key is provided by DNS, if you control the DNS, you can deny client from receiving the SNI key so that the browser does not encrypt the SNI

**Comment by luigi1809** [comment]
It seems bind has no option to block DNS request type but unbound has
https://serverfault.com/questions/744613/block-any-request-in-bind

It's worth looking at unbound

**Comment by mrbluecoat** [comment]
Very promising!  Thanks for your research, I really appreciate it.  I'm working on an embedded system with only 512MB of memory so I wonder if unbound or knot-resolver would be lightweight enough.  I'll look into them and FTL/dnsmasq: https://github.com/pi-hole/FTL/blob/master/dnsmasq_interface.c#L47

**Comment by mrbluecoat** [comment]
I'm not an iptables expert so I'm not sure if a variation of this would help: https://serverfault.com/a/843805

**Comment by luigi1809** [comment]
I would not use iptables for filtering DNS type query. I presume it would take too much ressource.

Filtering by the server should be more performant. To be tested with unbound
```
policy.add(function (req, query)
    if query.stype == kres.type.ANY then
            return policy.DROP
elseif query.stype == kres.type.ESNI then
            return policy.DROP
    end
end)
```

If you have a procedure to install unbound, please share it

**Comment by mrbluecoat** [comment]
Using https://docs.pi-hole.net/guides/unbound/ as a guide:

```
sudo apt install -y unbound dnsutils
wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/

cat >> /etc/unbound/unbound.conf.d/custom.conf <<EOL
server:
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 3
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    root-hints: "/var/lib/unbound/root.hints"
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1472
    prefetch: yes
    num-threads: 1
    so-rcvbuf: 1m
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
EOL

sudo service unbound start

dig sigfail.verteiltesysteme.net @127.0.0.1 -p 53 | grep SERVFAIL
dig sigok.verteiltesysteme.net @127.0.0.1 -p 53 | grep NOERROR
```
